apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: bank-mall
  labels:
    app: payment-service
    app.kubernetes.io/part-of: bank-mall
    app.kubernetes.io/component: payment
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP