apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
    app.kubernetes.io/part-of: bank-mall
    app.kubernetes.io/component: logging
spec:
  type: NodePort
  selector:
    app: loki
  ports:
  - name: http
    port: 3100
    targetPort: http
    nodePort: 30310
    protocol: TCP