apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-mall-config
  namespace: bank-mall
  labels:
    app.kubernetes.io/part-of: bank-mall
data:
  LOG_LEVEL: "INFO"
  SERVER_TOMCAT_THREADS_MAX: "200"
  SERVER_TOMCAT_THREADS_MIN_SPARE: "10"
  SPRING_PROFILES_ACTIVE: "prod"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  ACCOUNT_SERVICE_URL: "http://account-service:8082"
  PAYMENT_SERVICE_URL: "http://payment-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
  TZ: "Asia/Shanghai"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME_AUTH: "bank_auth"
  DB_NAME_ACCOUNT: "bank_account"
  DB_NAME_PAYMENT: "bank_payment"
  DB_NAME_NOTIFICATION: "bank_notification"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
  OTEL_TRACES_EXPORTER: "otlp"
