apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: jaeger
  labels:
    app: tempo
    app.kubernetes.io/part-of: bank-mall
spec:
  type: ClusterIP
  selector:
    app: tempo
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: jaeger
  labels:
    app: tempo
    app.kubernetes.io/part-of: bank-mall
spec:
  type: NodePort
  selector:
    app: tempo
  ports:
  - name: query
    port: 16686
    targetPort: 3200
    nodePort: 31686
    protocol: TCP
