apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-data-pv
  labels:
    app: tempo
    app.kubernetes.io/part-of: bank-mall
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/tempo-data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data-pvc
  namespace: tempo
  labels:
    app: tempo
    app.kubernetes.io/part-of: bank-mall
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: tempo-data-pv
