apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.image.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.auth.image.name }}
    {{- include "bank-mall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.auth.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.image.name }}
        {{- include "bank-mall.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.auth.image.name }}
        image: {{ include "bank-mall.image" (dict "imageName" .Values.auth.image.name "tag" .Values.auth.image.tag "Values" .Values) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.auth.ports.http }}
          protocol: TCP
        resources:
          {{- toYaml .Values.auth.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.auth.probes.liveness.path }}
            port: {{ .Values.auth.probes.liveness.port }}
          initialDelaySeconds: {{ .Values.auth.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.auth.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.auth.probes.readiness.path }}
            port: {{ .Values.auth.probes.readiness.port }}
          initialDelaySeconds: {{ .Values.auth.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.auth.probes.readiness.periodSeconds }}
