apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-bank-mall-and-monitoring
  namespace: jaeger
spec:
  podSelector:
    matchLabels:
      app: tempo
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 3200
  - from:
    - namespaceSelector:
        matchLabels:
          name: bank-mall
    ports:
    - protocol: TCP
      port: 4317
    - protocol: TCP
      port: 4318
    - protocol: TCP
      port: 3200
