apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-badger-pvc
  namespace: jaeger
  labels:
    app: jaeger
    app.kubernetes.io/part-of: bank-mall
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
