package com.bank.account.exception;

public enum ErrorCode {
    ACCOUNT_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    OPTIMISTIC_LOCK_CONFLICT,
    TRANSACTION_NOT_FOUND,
    DUPLICATE_IDEMPOTENCY_KEY,
    INVALID_AMOUNT,
    INVALID_REQUEST
}
